# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('gcm_regid', models.TextField()),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
