# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20160606_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.TextField()),
                ('notification', rest.models.JSONField(blank=True, null=True)),
                ('body', rest.models.JSONField(blank=True, null=True)),
                ('time_to_live', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.CharField(default=b'normal', max_length=6)),
                ('delay_while_idle', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_modified',
        ),
    ]
