# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20160606_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('registration_id', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
